version: "2"
services:
    gobuster:
        image: rabidang3ls/gobuster
        container_name: gobuster
        env_file: .env
        volumes:
            - ./myoutdir/$DIRNAME:/data
            - ./myoutdir/$DIRNAME/output:/data/output
        command: /bin/bash /opt/secdevops/start-gobuster.sh

    enumall:
        image: rabidang3ls/enumall
        container_name: enumall
        env_file: .env
        volumes:
            - ./myoutdir/$DIRNAME:/data
            - ./myoutdir/$DIRNAME/output:/data/output
        command: /bin/sh /opt/secdevops/start-enumall.sh

    sublist3r:
        image: rabidang3ls/sublist3r
        container_name: sublist3r
        env_file: .env
        volumes:
            - ./myoutdir/$DIRNAME:/data
            - ./myoutdir/$DIRNAME/output:/data/output
        command: /bin/sh /opt/secdevops/start-sublist3r.sh

    altdns:
        image: rabidang3ls/altdns
        container_name: altdns
        env_file: .env
        volumes:
            - ./myoutdir/$DIRNAME:/data
            - ./myoutdir/$DIRNAME/output:/data/output
        command: /bin/bash /opt/secdevops/wait-for-tools-start-altdns.sh
